PUT http://127.0.0.1:5000/api/v1/admin/update-user-status/70b1a8b5-6691-4f76-92d0-82b0c7c1edc6
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNzU1NjE0NjM1LCJleHAiOjE3NTU2MjU0MzV9.Kgd_BIVS9Gg17P_vq07Zax_wIgkoh96OvrQu-Z6DoIc
content-type: application/json

{
  "status": "approved"
}

### 
POST http://127.0.0.1:5000/api/v1/auth/register
content-type: application/json

{
    "email": "test@mail.com",
    "fullName": "John",
    "balance": 400,
    "password": "12345678",
    "country": "user",
    "referredBy": "jamie",
    "phone": "09000000000"
  }

### login URL
POST http://127.0.0.1:5000/api/v1/auth/login
content-type: application/json

{
    "identifier": "admin@mail.com",
    "password": "admin-skye"
}
### {
#     "identifier": "charletontech",
#     "password": "123"
# }
# {
#     "email": "admin@mail.com",
#     "password": "admin-neche"
# }

### {
#     "email": "admin@mail.com",
#     "password": "admin-neche"
# }


GET http://localhost:5000/api/v1/dashboard/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcwYjFhOGI1LTY2OTEtNGY3Ni05MmQwLTgyYjBjN2MxZWRjNiIsImVtYWlsIjoidWthY2hhcmxpZUBnbWFpbC5jb20iLCJpYXQiOjE3NDU4ODA4OTAsImV4cCI6MTc0NTg4ODA5MH0.mycOPUae0JRFtfWuDstqh3uMNvkNE0qUieV_f_pDe50



### Dashboard
PUT http://localhost:5000/api/v1/admin/all-users
credentials: "include"
# authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M


### create-elite-video
POST http://127.0.0.1:85/api/v1/elite/create-elite-video
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dataFields"

{"title": "Maverick Top Gun","description": "American Sci-Fi movie",
"category": "Movie","directors": ["John", "Doe"],
"starring": ["John", "Doe"],"genres": "Action",
"audioLanguage": "English","producers": ["Tom Cruise", "Fox Studios"],
"studio": "Fox Studio","approvalStatus": false}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="phone1.jpg"
Content-Type: image/jpeg

< ./phone1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="SampleVideo.mp4"
Content-Type: video/jpeg

< ./SampleVideo.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="sample.srt"
Content-Type: text/plain

< ./sample.srt
------WebKitFormBoundary7MA4YWxkTrZu0gW--

# SKYE TRADE ENDPOINTS
### admin login
POST http://127.0.0.1:5000/api/v1/auth/login
content-type: application/json

{
  "identifier": "admin@mail.com",
  "password": "admin-skye"
}

### edit-trade
PUT http://127.0.0.1:5000/api/v1/admin/edit-trade/da250196-fa7a-4360-be08-2540a3d626ba
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNzQ2ODQyOTkyLCJleHAiOjE3NDY4NTM3OTJ9.LTXxwt8go96auRA8kbS7rYDUzQejZP12J8JLPV8wrfI
content-type: application/json

{
  "target": 20,
  "profit": 10
}


### get-all-trades
GET http://127.0.0.1:5000/api/v1/admin/all-trades
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNzQ2ODQyOTkyLCJleHAiOjE3NDY4NTM3OTJ9.LTXxwt8go96auRA8kbS7rYDUzQejZP12J8JLPV8wrfI

### get-all-kyc
GET http://127.0.0.1:5000/api/v1/admin/all-kyc
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNzQ2ODQyOTkyLCJleHAiOjE3NDY4NTM3OTJ9.LTXxwt8go96auRA8kbS7rYDUzQejZP12J8JLPV8wrfI

### edit-kyc
PUT http://127.0.0.1:5000/api/v1/admin/edit-kyc/0e62be63-e103-4ac0-bb9c-03e2be572128
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNzQ2ODQyOTkyLCJleHAiOjE3NDY4NTM3OTJ9.LTXxwt8go96auRA8kbS7rYDUzQejZP12J8JLPV8wrfI
content-type: application/json

{
  "status": "approved"
}

### get-all-users
GET http://127.0.0.1:5000/api/v1/admin/all-users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNzQ2ODQyOTkyLCJleHAiOjE3NDY4NTM3OTJ9.LTXxwt8go96auRA8kbS7rYDUzQejZP12J8JLPV8wrfI

### edit-user
PUT http://127.0.0.1:5000/api/v1/admin/edit-user/70b1a8b5-6691-4f76-92d0-82b0c7c1edc6
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNzQ2ODQyOTkyLCJleHAiOjE3NDY4NTM3OTJ9.LTXxwt8go96auRA8kbS7rYDUzQejZP12J8JLPV8wrfI
content-type: application/json

{
  "action": "switchAccount",
  "accountType": "Pro Account",
  "amount": 150
}

### manage withdrawal request
PUT http://127.0.0.1:5000/api/v1/admin/manage-withdrawal-request/c3b69392-a55f-462b-830d-c41f98bb1bba
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNzQ2ODQyOTkyLCJleHAiOjE3NDY4NTM3OTJ9.LTXxwt8go96auRA8kbS7rYDUzQejZP12J8JLPV8wrfI
content-type: application/json

{"status": "approved"}




### get-elite-video-views-count
GET http://127.0.0.1:85/api/v1/elite/get-all-elite-video-views-count/b66f23e0-ef66-4522-9faa-96db28990b32
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M


### webhook-video-played
GET http://127.0.0.1:85/api/v1/elite/webhook/video-played/b66f23e0-ef66-4522-9faa-96db28990b32


### webhook-video-ended
POST http://127.0.0.1:85/api/v1/elite/webhook/video-ended
content-type: application/json

{
  "videoId": "b66f23e0-ef66-4522-9faa-96db28990b32",
  "minutesWatched": 2,
  "finishedWatching": false
}




### create-elite-music
POST http://127.0.0.1:85/api/v1/elite/create-elite-music
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dataFields"

 { 
  "trackName": "I'm Alive",
  "trackDescription": "Nostalgic RnB song about love and how loved one mean so much to us",
  "trackDuration": "00:04:24",
  "artistName": "Celine Dion",
  "albumName": "Forever",
  "genre": "Rhythm n Blues",
  "language": "Eng",
  "releaseDate": "1/7/2002"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="phone1.jpg"
Content-Type: image/jpeg

< ./phone1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="SampleMusic.mp3"
Content-Type: audio/mpeg

< ./SampleMusic.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### get-elite-music
GET http://127.0.0.1:85/api/v1/elite/get-all-elite-music
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M


### get-elite-music-analytics
GET http://127.0.0.1:85/api/v1/elite/get-elite-music-analytics/8d81aac1-7b2f-4fef-9d64-a12c35196a5c
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M

### get-elite-music-views-count
GET http://127.0.0.1:85/api/v1/elite/get-elite-music-streams-count/8d81aac1-7b2f-4fef-9d64-a12c35196a5c
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M


### webhook-music-played
GET http://127.0.0.1:85/api/v1/elite/webhook/music-played/0ce49e21-7ac7-45ba-99cb-99948681f890
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M


### webhook-music-ended
POST http://127.0.0.1:85/api/v1/elite/webhook/music-ended
content-type: application/json

{
  "musicId": "0ce49e21-7ac7-45ba-99cb-99948681f890",
  "minutesListened": 2.5,
  "finishedPlaying": true
}


### create-elite-podcast
POST http://127.0.0.1:85/api/v1/elite/create-elite-podcast
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dataFields"

 { 
  "title": "I'm Alive",
  "description": "Podcast about love and relationship",
  "language": "Eng",
  "category": "love and relationship"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="phone1.jpg"
Content-Type: image/jpeg

< ./phone1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### add-podcast-episode
POST http://127.0.0.1:85/api/v1/elite/add-podcast-episode
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dataFields"

 {
  "episodeTitle": "The love Languages",
  "podcastId": "85fb80fa-b391-42bb-bf5e-b187fd92c703",
  "description": "The love Languages",
  "genre": "Emotional health",
  "guestName": "Sheyla Strong",
  "duration": "00:42:11",
  "releaseDate": "2025/02/12"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="phone1.jpg"
Content-Type: image/jpeg

< ./phone1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="SampleMusic.mp3"
Content-Type: audio/mpeg

< ./SampleMusic.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### get-podcast
GET http://127.0.0.1:85/api/v1/elite/get-podcasts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M

### get-podcast-episodes
GET http://127.0.0.1:85/api/v1/elite/get-podcast-episodes/85fb80fa-b391-42bb-bf5e-b187fd92c703
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M

### get-podcast-episode-analytic
GET http://127.0.0.1:85/api/v1/elite/get-podcast-episode-analytic/3c0344c9-7d48-4a64-ba21-9f7ef174412e
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M


### podcast-played-webhook
POST http://127.0.0.1:85/api/v1/elite/webhook/podcast-played
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M
content-type: application/json

{
  "viewerId":"055",
  "podcastEpisodeId": "3c0344c9-7d48-4a64-ba21-9f7ef174412e",
  "viewerCountry": "Nigeria",
  "durationListened": "00:48:11",
  "completedPlaying": true
}


### upload-book
POST http://127.0.0.1:85/api/v1/elite/upload-book
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dataFields"

 {
        "title": "Rich Dad, Poor Dad",
        "bookDescription": "financial management book teaching wealth management",
        "genre": "finance",
        "language": "Eng",
        "bookPrice": 5000,
        "totalPages": 84,
        "dimension": "7.5 x 10 x 10 inches",
        "publisherName": "Ronald Jameson",
        "publicationDate": "10/2/2025",
        "stickyNotes": true,
        "pageFlipOption": true,
        "authorName": "Donald J. Thompson",
        "authorDescription": "Financial expert with 20 years experience"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="coverImage"; filename="phone1.jpg"
Content-Type: image/jpeg

< ./phone1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="authorImage"; filename="phone1.jpg"
Content-Type: image/jpeg

< ./phone1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="bookFile"; filename="samplePdf2.pdf"
Content-Type: application/pdf

< ./samplePdf2.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### get-elite-books
GET http://127.0.0.1:85/api/v1/elite/get-books
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M


### edit-elite-book
PUT http://127.0.0.1:85/api/v1/elite/edit-book-data/:6
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M
content-type: application/json

{
        "title": "Rich Dad, Poor Dad - part 1",
        "bookDescription": "financial management book teaching wealth management",
        "genre": "finance",
        "language": "Eng",
        "bookPrice": 5000,
        "totalPages": 84,
        "dimension": "7.5 x 10 x 10 inches",
        "publisherName": "Ronald Jameson",
        "publicationDate": "10/2/2025",
        "stickyNotes": false,
        "pageFlipOption": false,
        "authorName": "Donald J. Thompson jr",
        "authorDescription": "Financial expert with 20 years experience"
}

### delete-elite-book
GET http://127.0.0.1:85/api/v1/elite/delete-book/5
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzNGYyYWM0LWRmMDMtNGI0NS1iNTdiLWMzYWMxNDI5ZTQzOCIsImlhdCI6MTczODcwNDc4NSwiZXhwIjoxNzQzODg4Nzg1fQ.4ZBBv-xNjVlD4x6IQAIOWm1okGYHhjW1oIvQMC0UU5M
