module.exports = {
    validateGetEditStoresObj: require("./getEditStoreObj"),
    validateGetEditStoreStatusObj: require("./getEditStoreStatusObj"),
    validateAddStoreObj: require("./addStore"),
    validateAddReturnPolicyObj: require("./addReturnPolicy"),
    validateAddDefaultReturnAddressObj: require("./addDefaultReturnAddress"),
    validateAddShippingDetailsObj: require("./addShippingDetails"),
    validateAddStoreDaysObj: require("./addStoreDays"),
    validateAddStoreTaxConfirmationObj: require("./addStoreTaxConfirmation"),
    validateAddStoreTaxObj: require("./addStoreTax"),
    validateAddStoreReturnResolutionObj: require("./addStoreReturnResolution"),
    validateEditStoreReturnResolutionObj: require("./editStoreReturnResolution"),
    validateRemoveStoreReturnResolutionObj: require("./removeStoreReturnResolution"),
    validateEditStoreReturnResolutionDefaultObj: require("./editStoreReturnResolutionDefault"),
    validateAddAppSettingObj: require("./addAppSetting"),
    validateChangeNameObj: require("./addChangeName"),
    validateAddRequestChangeEmailObj: require("./addRequestChangeEmail"),
    validateAddChangeEmailObj: require("./addChangeEmail"),
    validateAddRequestChangePhoneObj: require("./addRequestChangePhone"),
    validateAddChangePhoneObj: require("./addChangePhone"),
    validateAddChangePasswordObj: require("./addChangePassword"),
    validateAddVerificationMethodObj: require("./addVerificationMethod"),
}
  